Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
Traceback (most recent call last):
  File "./probing.py", line 55, in <module>
    _, _, embedding_dimension = X.shape
AttributeError: 'NpzFile' object has no attribute 'shape'
