Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_GTT_layer_0_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_2_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_8_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_GTT_layer_0_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_2_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_8_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_GTT_layer_0_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_2_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_8_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_GTT_layer_0_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_2_bert-uncased_epoch20_muc1700.npy'
Traceback (most recent call last):
  File "./probing.py", line 28, in <module>
    X = np.load(
  File "/home/zw545/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../X/X_TANL_layer_8_bert-uncased_epoch20_muc1700.npy'
